import {
  RouletteConfiguration,
  RouletteNumberProps,
  RouletteStats,
} from "@/interfaces/interfaces";

export const mockConfigurationMock: RouletteConfiguration = {
  positionToId: [
    37, 27, 10, 25, 29, 12, 8, 19, 31, 18, 6, 21, 33, 16, 4, 23, 14, 0,
  ],
  results: [
    "00",
    "27",
    "10",
    "25",
    "29",
    "12",
    "8",
    "19",
    "31",
    "18",
    "6",
    "21",
    "33",
    "16",
    "4",
    "23",
    "14",
    "0",
  ],
  colors: [
    "green",
    "red",
    "black",
    "red",
    "black",
    "red",
    "black",
    "red",
    "black",
    "red",
    "black",
    "red",
    "black",
    "red",
    "black",
    "red",
    "red",
    "green",
  ],
  slots: 38,
  name: "doubleZero",
};

export const expectedConfigurationMock: RouletteNumberProps[] = [
  { rouletteResult: 37, rouletteNumber: "00", rouletteColor: "green" },
  { rouletteResult: 27, rouletteNumber: "27", rouletteColor: "red" },
  { rouletteResult: 10, rouletteNumber: "10", rouletteColor: "black" },
  { rouletteResult: 25, rouletteNumber: "25", rouletteColor: "red" },
  { rouletteResult: 29, rouletteNumber: "29", rouletteColor: "black" },
  { rouletteResult: 12, rouletteNumber: "12", rouletteColor: "red" },
  { rouletteResult: 8, rouletteNumber: "8", rouletteColor: "black" },
  { rouletteResult: 19, rouletteNumber: "19", rouletteColor: "red" },
  { rouletteResult: 31, rouletteNumber: "31", rouletteColor: "black" },
  { rouletteResult: 18, rouletteNumber: "18", rouletteColor: "red" },
  { rouletteResult: 6, rouletteNumber: "6", rouletteColor: "black" },
  { rouletteResult: 21, rouletteNumber: "21", rouletteColor: "red" },
  { rouletteResult: 33, rouletteNumber: "33", rouletteColor: "black" },
  { rouletteResult: 16, rouletteNumber: "16", rouletteColor: "red" },
  { rouletteResult: 4, rouletteNumber: "4", rouletteColor: "black" },
  { rouletteResult: 23, rouletteNumber: "23", rouletteColor: "red" },
  { rouletteResult: 14, rouletteNumber: "14", rouletteColor: "red" },
  { rouletteResult: 0, rouletteNumber: "0", rouletteColor: "green" },
];

export const rouletteStatsMock: RouletteStats[] = [
  { result: 36, count: 5 },
  { result: 27, count: 5 },
  { result: 10, count: 5 },
  { result: 25, count: 6 },
  { result: 29, count: 6 },
  { result: 12, count: 6 },
  { result: 8, count: 6 },
  { result: 19, count: 6 },
  { result: 31, count: 6 },
  { result: 18, count: 7 },
  { result: 6, count: 7 },
  { result: 21, count: 7 },
  { result: 33, count: 7 },
  { result: 16, count: 8 },
  { result: 4, count: 9 },
  { result: 23, count: 9 },
  { result: 14, count: 9 },
  { result: 0, count: 10 },
];

export const expectedRouletteStatisticsTableMock: RouletteNumberProps[] = [
  {
    rouletteResult: 36,
    rouletteNumber: "00",
    rouletteColor: "green",
    rouletteNumberCount: 5,
  },
  {
    rouletteResult: 27,
    rouletteNumber: "27",
    rouletteColor: "red",
    rouletteNumberCount: 5,
  },
  {
    rouletteResult: 10,
    rouletteNumber: "10",
    rouletteColor: "black",
    rouletteNumberCount: 5,
  },
  {
    rouletteResult: 25,
    rouletteNumber: "25",
    rouletteColor: "red",
    rouletteNumberCount: 6,
  },
  {
    rouletteResult: 29,
    rouletteNumber: "29",
    rouletteColor: "black",
    rouletteNumberCount: 6,
  },
  {
    rouletteResult: 12,
    rouletteNumber: "12",
    rouletteColor: "red",
    rouletteNumberCount: 6,
  },
  {
    rouletteResult: 8,
    rouletteNumber: "8",
    rouletteColor: "black",
    rouletteNumberCount: 6,
  },
  {
    rouletteResult: 19,
    rouletteNumber: "19",
    rouletteColor: "red",
    rouletteNumberCount: 6,
  },
  {
    rouletteResult: 31,
    rouletteNumber: "31",
    rouletteColor: "black",
    rouletteNumberCount: 6,
  },
  {
    rouletteResult: 18,
    rouletteNumber: "18",
    rouletteColor: "red",
    rouletteNumberCount: 7,
  },
  {
    rouletteResult: 6,
    rouletteNumber: "6",
    rouletteColor: "black",
    rouletteNumberCount: 7,
  },
  {
    rouletteResult: 21,
    rouletteNumber: "21",
    rouletteColor: "red",
    rouletteNumberCount: 7,
  },
  {
    rouletteResult: 33,
    rouletteNumber: "33",
    rouletteColor: "black",
    rouletteNumberCount: 7,
  },
  {
    rouletteResult: 16,
    rouletteNumber: "16",
    rouletteColor: "red",
    rouletteNumberCount: 8,
  },
  {
    rouletteResult: 4,
    rouletteNumber: "4",
    rouletteColor: "black",
    rouletteNumberCount: 9,
  },
  {
    rouletteResult: 23,
    rouletteNumber: "23",
    rouletteColor: "red",
    rouletteNumberCount: 9,
  },
  {
    rouletteResult: 14,
    rouletteNumber: "14",
    rouletteColor: "red",
    rouletteNumberCount: 9,
  },
  {
    rouletteResult: 0,
    rouletteNumber: "0",
    rouletteColor: "green",
    rouletteNumberCount: 10,
  },
];

export const expectedRouletteNumbersStatisticsMock: RouletteNumberProps[] = [
  {
    rouletteNumberCount: 5,
    rouletteResult: 0,
    rouletteNumber: "0",
    rouletteColor: "green",
  },
  {
    rouletteNumberCount: 3,
    rouletteResult: 1,
    rouletteNumber: "1",
    rouletteColor: "red",
  },
  {
    rouletteNumberCount: 2,
    rouletteResult: 36,
    rouletteNumber: "00",
    rouletteColor: "green",
  },
];

export const expectedColdCategorizedMock: RouletteNumberProps[] = [
  {
    rouletteResult: 36,
    rouletteNumber: "00",
    rouletteColor: "green",
    rouletteNumberCount: 5,
  },
  {
    rouletteResult: 27,
    rouletteNumber: "27",
    rouletteColor: "red",
    rouletteNumberCount: 5,
  },
  {
    rouletteResult: 10,
    rouletteNumber: "10",
    rouletteColor: "black",
    rouletteNumberCount: 5,
  },
  {
    rouletteResult: 25,
    rouletteNumber: "25",
    rouletteColor: "red",
    rouletteNumberCount: 6,
  },
  {
    rouletteResult: 29,
    rouletteNumber: "29",
    rouletteColor: "black",
    rouletteNumberCount: 6,
  },
];
